ALTER TABLE storm_runs
  ADD COLUMN IF NOT EXISTS position_x DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS position_y DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS width DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS height DOUBLE PRECISION;
